// HYco 대시보드 정적 데이터
// 소스: C:/Projects_local/_bot/ 파일 기반
// 마지막 동기화: 2026-03-22 (post_work.py 자동 동기화)

import type {
  Project,
  KpiSnapshot,
  Approval,
  HyDirectTask,
  LogEntry,
  SystemScript,
} from './types';

export const KPI: KpiSnapshot = {
  monthlyRevenue: '₩0',
  monthlyRevenueStatus: 'yellow',
  adSenseSites: 2,
  weeklyCommits: 25,
  pendingDecisions: 0,
  inboxCount: 0,
  activeProjects: 4,
};

export const PROJECTS: Project[] = [
  {
    slug: 'chehumzip',
    name: 'ChehumZip',
    emoji: '🗂️',
    completion: 95,
    status: 'active',
    domain: 'exp-zip.co.kr',
    revenueModel: 'Google AdSense',
    revenueStatus: '재심사 대기 (2026-03-06 제출)',
    color: '#4f46e5',
    description: '40개 체험단 플랫폼 캠페인 통합 검색엔진',
    techStack: ['Next.js 16', 'Supabase', 'Kakao Map', 'Python Playwright'],
    nextTasks: [
      'Search Console 등록 (HY 직접 — 브라우저 이슈 해소 후)',
      '네이버 서치어드바이저 등록',
      'AdSense 재심사 결과 확인 (3/06 제출, 2주+ 경과)',
      'AdSense 광고 슬롯 최적화 (재심사 통과 후)',
    ],
    pendingDecisions: [],
    lastUpdated: '2026-03-21',
    brainHighlights: [
      '✅ (03-21) Vercel KV 채택 → route.ts 캐시 레이어 교체 완료',
      '✅ /platform/[slug] 40페이지 SSG 완료',
      '✅ 카테고리 11페이지 SSG 완료',
      '✅ SEO 극대화 (meta+OG+JSON-LD+sitemap)',
      '✅ 지도 UX 3루프 고도화 (마커 클러스터링, 팝업, 터치)',
      '✅ 검색 강화 (자동완성, 초성 검색, debounce 300ms)',
      '✅ 크롤러 43개 통합, validators 8단계',
    ],
  },
  {
    slug: 'toolsajang',
    name: 'Toolsajang',
    emoji: '🔧',
    completion: 97,
    status: 'active',
    domain: 'toolsajang.com',
    revenueModel: 'Google AdSense',
    revenueStatus: '활성 — 슬롯 7개 (2026-03-20 git push)',
    color: '#10b981',
    description: '한국 소상공인·자영업자 대상 무료 비즈니스 계산기 플랫폼',
    techStack: ['Next.js 16', 'Tailwind CSS', 'MDX', 'Gemini Flash'],
    nextTasks: [
      'AI 툴 2종 활성화 — isActive: true (코드 1줄, HY 확인 후)',
      'Search Console + 네이버 서치어드바이저 등록',
      '4월: 신규 계산기 추가 (창업비용, 매출예측, 배달순이익)',
    ],
    pendingDecisions: [],
    lastUpdated: '2026-03-21',
    brainHighlights: [
      '✅ 계산기 28종 (배달앱수수료·인건비비율·임대료비율 3개 추가)',
      '✅ 장사 팁 MDX 68편',
      '✅ AdSense 승인 완료 + 슬롯 7개 배치',
      '✅ GA4 연결 (G-N53PEQP8KY)',
      '✅ AI 툴 구현 완료 (Gemini Flash, $5/주 비용방어)',
      '✅ SEO 극대화 (계산기+팁 JSON-LD, 내부 링크)',
    ],
  },
  {
    slug: 'hydrogen',
    name: 'hydrogen_tools',
    emoji: '⚡',
    completion: 90,
    status: 'active',
    domain: 'web-kappa-navy.vercel.app',
    revenueModel: 'Freemium (Excel + 구독)',
    revenueStatus: 'Excel 6파일 준비 완료 — Gumroad 계정 대기',
    color: '#f59e0b',
    description: '수소 에너지 실무자를 위한 LCOH 계산기 + 데이터 플랫폼 (H2Prism)',
    techStack: ['Next.js 16', 'Tailwind v4', 'Recharts', 'i18n (ko/en)'],
    nextTasks: [
      'Gumroad 계정 생성 + 판매 페이지 세팅 (파일 준비 완료)',
      '데이터 DB 확장 (기업 50+ 프로젝트 50+)',
      'Substack 뉴스레터 (4월 시작)',
    ],
    pendingDecisions: [],
    lastUpdated: '2026-03-21',
    brainHighlights: [
      '✅ (03-21) 브랜드명 H2Prism 확정',
      '✅ (03-21) 판매 채널: Gumroad + 자체 사이트 (Gumroad 먼저)',
      '✅ (03-21) 판매 시점 유예, 도메인 3/25 이후 유예',
      '✅ Excel 상품 6파일 완성 (Tier1/2/3 한/영)',
      '✅ 블로그 영문 포스트 5편 (SSG 31페이지)',
      '✅ LCOH 계산기 3단계 티어 (DCF, NPV/IRR, 시나리오)',
      '✅ 수소 생산 경로 8종 (PEM/ALK/SMR/Coal 등)',
      '✅ 한/영 다국어 + 화폐 전환 4종',
    ],
  },
  {
    slug: 'wheretogo',
    name: 'wheretogo',
    emoji: '📍',
    completion: 70,
    status: 'active',
    domain: '네이버 블로그',
    revenueModel: '블로그 광고 + 연계 유입',
    revenueStatus: '구축 중 (첫 발행 준비됨)',
    color: '#06b6d4',
    description: '서울·수도권 데이트·외출 정보 AI 블로그 자동 생성 CLI',
    techStack: ['Python 3.10+', 'Claude API', 'Playwright', 'BeautifulSoup'],
    nextTasks: [
      '첫 10편 정식 발행 (테스트 3편 품질 검증 완료)',
      'C-Rank 기초 작업 (프로필, 카테고리, 이웃추가)',
      '주 3~5회 발행 루틴 정착',
    ],
    pendingDecisions: [],
    lastUpdated: '2026-03-21',
    brainHighlights: [
      '✅ (03-21) 블로그명 "어디갈까" 확정 (채널 ID: wheretogo)',
      '✅ 콘텐츠 3편 테스트 생성 및 품질 검증',
      '✅ pytest 70개 통과 (28→70개)',
      '✅ --images 파이프라인 추가',
      '✅ 3가지 생성 모드 (주제/패러프레이징/리서치)',
      '✅ 콘텐츠 유형 6종 + CTA 전략',
    ],
  },
  {
    slug: 'shorts',
    name: 'Shorts Creator',
    emoji: '🎬',
    completion: 97,
    status: 'monitoring',
    domain: 'korean-shorts-dashboard.vercel.app',
    revenueModel: 'YouTube 광고 (예정)',
    revenueStatus: '운영 안정화 단계',
    color: '#8b5cf6',
    description: '"About Korean" YouTube Shorts 자동 제작 파이프라인',
    techStack: ['Next.js 15', 'Remotion 4', 'Supabase', 'ElevenLabs', 'Claude/GPT/Gemini'],
    nextTasks: [
      'Batch 2 영상 3편 제작 (빨리빨리, 화이팅, 대박)',
      'YouTube 링크 입력 시 자동 완료 처리',
      'Phase 16 E2E 렌더링 플로우 검증',
    ],
    pendingDecisions: [],
    lastUpdated: '2026-03-21',
    brainHighlights: [
      '✅ YouTube OAuth URI 등록 확인 (47일 대기 해소)',
      '✅ 환경변수 정비 완료',
      '✅ Supabase 복구 (Healthy)',
      '✅ Batch 2 파이프라인 구현',
      '✅ 3채널 트래킹 (Google Sheets + Drive + SSE)',
    ],
  },
  {
    slug: 'pickntry',
    name: 'pickntry',
    emoji: '🛒',
    completion: 80,
    status: 'monitoring',
    domain: 'pickntry.vercel.app',
    revenueModel: '미정',
    revenueStatus: '런치 시점 대기',
    color: '#ec4899',
    description: '픽앤트라이 커머스 플랫폼',
    techStack: ['Next.js', 'Supabase', 'React'],
    nextTasks: [
      'Supabase phone 컬럼 추가 (스키마 마이그레이션)',
      '런치 스위치 전환 DEMO_MODE=false',
    ],
    pendingDecisions: [],
    lastUpdated: '2026-03-17',
    brainHighlights: [
      '✅ 보안 이슈 9건 수정',
      '✅ ESLint 15→0',
      '✅ 코드 스플리팅 23% 감소',
    ],
  },
];

// 승인 대기 없음 — 모두 결정 완료
export const APPROVALS: Approval[] = [];

export const HY_DIRECT_TASKS: HyDirectTask[] = [
  { item: 'Search Console 등록', project: 'ChehumZip + Toolsajang', memo: '브라우저 이슈 해소 후 시크릿 모드로 재시도' },
  { item: '네이버 서치어드바이저 등록', project: 'ChehumZip + Toolsajang', memo: 'HY 직접 등록 필요' },
  { item: 'AI 툴 isActive: true 변경', project: 'Toolsajang', memo: 'src/data/tools.ts 코드 1줄 — Gemini API 준비 완료' },
  { item: 'AdSense 재심사 결과 확인', project: 'ChehumZip', memo: '2026-03-06 제출, 2주+ 경과 — Google 콘솔 확인' },
  { item: 'Gumroad 계정 생성', project: 'hydrogen_tools', memo: 'Excel 파일 패키징 완료, 판매채널 Gumroad+자체 결정됨' },
];

export const LOGS: LogEntry[] = [
  {
    date: '2026-03-22',
    sessionType: '문서 최신화 + 대시보드 구축',
    summary: '문서 시스템 업데이트 + HYco 대시보드 웹앱 구축 + Vercel 배포',
    items: [
      { category: '문서', title: 'WORK_STATUS.md 업데이트', result: '리팩토링 결과 반영', status: 'done' },
      { category: '문서', title: 'hq_status.md 최신화', result: '2026-03-22 기준 갱신', status: 'done' },
      { category: '문서', title: 'agent_log 추가', result: '2026-03-22 세션 로그', status: 'done' },
      { category: '대시보드', title: 'HYco Dashboard 구축', result: 'Next.js 16 + Tailwind v4', status: 'done' },
      { category: '배포', title: 'GitHub + Vercel 배포', result: 'PseudomonasFriend/hyco-dashboard', status: 'done' },
      { category: '의사결정', title: 'HY 7건 승인 완료', result: 'wheretogo블로그명·pickntry보류·ChehumZip KV·hydrogen 4건', status: 'done' },
    ],
  },
  {
    date: '2026-03-21',
    sessionType: 'Phase D 완료 + SEO 극대화 + 기능 고도화',
    projectSlug: 'chehumzip',
    summary: 'GA4 연결, SEO 극대화, Phase D R1/R2/R3 완료, AI 툴, Excel 완성 — 25건+',
    items: [
      { category: 'Analytics', title: 'GA4 연결 (Toolsajang + ChehumZip)', result: 'G-N53PEQP8KY, G-DL9MXNY8GW', status: 'done' },
      { category: 'SEO', title: 'ChehumZip SEO 극대화', result: 'meta+OG+JSON-LD+sitemap 전면 적용', status: 'done' },
      { category: 'SEO', title: 'Toolsajang SEO 극대화', result: '계산기 25종+팁 68편 JSON-LD', status: 'done' },
      { category: '기능', title: 'Toolsajang AI 툴 구현', result: 'Gemini Flash, $5/주 비용방어', status: 'done' },
      { category: '기능', title: '계산기 3개 추가', result: '25→28종 (배달앱수수료·인건비·임대료)', status: 'done' },
      { category: '기능', title: 'ChehumZip 지도 UX 3루프', result: '4인 팀 피드백 3라운드', status: 'done' },
      { category: '기능', title: 'ChehumZip 검색 강화', result: '자동완성+초성+debounce 300ms', status: 'done' },
      { category: '데이터', title: 'hydrogen Excel 6파일', result: 'Tier1/2/3 한/영, 워터마크+패키징', status: 'done' },
      { category: '콘텐츠', title: 'wheretogo 콘텐츠 3편', result: '품질 검증 통과, 발행 준비됨', status: 'done' },
      { category: '확인', title: 'Search Console 등록 시도', result: '브라우저 이슈로 보류', status: 'skipped' },
    ],
  },
  {
    date: '2026-03-20',
    sessionType: 'AdSense + 인프라 + 전 프로젝트 고도화',
    summary: 'AdSense 슬롯 7개, Supabase 복구, 크롤러 43개, 멀티에이전트 시스템 구현 — 30건',
    items: [
      { category: '수익', title: 'Toolsajang AdSense 슬롯 7개', result: 'git push (f9e7526), 광고 수익 시작', status: 'done' },
      { category: '인프라', title: 'Shorts Supabase 복구', result: 'Resume→Healthy, 헬스체크 cron 추가', status: 'done' },
      { category: '크롤러', title: 'ChehumZip 43개 크롤러', result: '전체 1회 실행 완료', status: 'done' },
      { category: '시스템', title: '멀티에이전트 시스템 구현', result: '10개 컴포넌트, CLAUDE.md 6개', status: 'done' },
      { category: '시스템', title: '설계문서 v2 (Mermaid)', result: '4인팀 피드백 15개 문제 수정', status: 'done' },
    ],
  },
  {
    date: '2026-03-19',
    sessionType: 'ChehumZip 고도화',
    projectSlug: 'chehumzip',
    summary: 'Phase D R2 — SSG, API 최적화, 크롤러 에러 핸들링',
    items: [
      { category: '기능', title: '/platform/[slug] 40페이지 SSG', result: '빌드 성공', status: 'done' },
      { category: '성능', title: 'API O(n²)→O(n) 최적화', result: '응답속도 개선', status: 'done' },
    ],
  },
];

export const SYSTEM_SCRIPTS: SystemScript[] = [
  { name: '텔레그램 봇', file: 'bot.py', status: 'running', description: '24개 커맨드 운영 중' },
  { name: '데일리 브리핑', file: 'briefing.py', status: 'running', description: '7:30 자동 실행 (_HQ/Daily/ 기반)' },
  { name: 'ARIA v7', file: 'aria_router.py', status: 'ready', description: '4단계 라우팅 (73개 테스트 통과)' },
  { name: 'CEO 알림', file: 'notify_ceo.py', status: 'ready', description: '마일스톤 완료 시 즉시 전송' },
  { name: '카드뉴스 v2', file: 'card_news_v2.py', status: 'idle', description: '5포맷 x 다크/라이트 x 7컬러' },
  { name: 'PPT 생성기', file: 'ppt_generator.py', status: 'idle', description: '8레이아웃 컨설팅급 보고서' },
  { name: '에이전트 워커', file: 'agent_worker.py', status: 'running', description: '4단계 점진적 공개 문서 체인' },
  { name: '승인 큐', file: 'task_queue.py', status: 'ready', description: 'ARIA 작업 승인 관리' },
];
